trigger:
- dev  

pool:
  name: 'default'
  demands:
  - Agent.Name -equals GTC-VM-014

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Deployment Start"
      cd /22css/agent/_work/2/s/QED
      npm i  
      echo "copying files to gtc-vm-023"
      rsync -avz /22css/agent/_work/2/s/QED/ root@192.168.1.98:/22css/QED/
      echo "copied to gtc-vm-023"
      ssh root@192.168.1.98 << 'ENDSSH'
      if [ $? -ne 0 ]; then
         echo "Failed to connect to the hosting server"
         exit 1
      fi
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
      nvm use default
      cd /22css/QED/
      pm2 delete QED
      pm2 save
      pm2 start "ng serve" --name QED
      pm2 save
      pm2 status
      echo "Deployment Done"