// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.Data.Models;

public partial class Case
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public string IssueDescripition { get; set; }

    public int CtstatusId { get; set; }

    public int CtpriorityId { get; set; }

    public int CreatedBy { get; set; }

    public DateTimeOffset CreatedDateTime { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTimeOffset? UpdatedDateTime { get; set; }
}