// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.Data.Models;

public partial class CommonType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Ctid { get; set; }

    public string Keys { get; set; }

    public string Code { get; set; }

    public bool IsDeleted { get; set; }

    public int CreatedBy { get; set; }

    public DateTimeOffset CreatedDateTime { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTimeOffset? UpdatedDateTime { get; set; }
}