// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRM.Data.Models;

public partial class CRMDEVContext : DbContext
{
    public CRMDEVContext(DbContextOptions<CRMDEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<Case> Cases { get; set; }

    public virtual DbSet<CommonType> CommonTypes { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<CustomerProfile> CustomerProfiles { get; set; }

    public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.AppUserId).HasColumnName("AppUserID");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<Case>(entity =>
        {
            entity.ToTable("Case");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CtpriorityId).HasColumnName("CTPriorityID");
            entity.Property(e => e.CtstatusId).HasColumnName("CTStatusID");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.IssueDescripition).IsRequired();
        });

        modelBuilder.Entity<CommonType>(entity =>
        {
            entity.ToTable("CommonType");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Code).HasMaxLength(30);
            entity.Property(e => e.Ctid).HasColumnName("CTID");
            entity.Property(e => e.Keys).HasMaxLength(4);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.ToTable("CustomerAddress");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BillingAppSuite).HasMaxLength(500);
            entity.Property(e => e.BillingCity).HasMaxLength(500);
            entity.Property(e => e.BillingCountry).HasMaxLength(500);
            entity.Property(e => e.BillingPostalCode).HasMaxLength(500);
            entity.Property(e => e.BillingStateProvince).HasMaxLength(500);
            entity.Property(e => e.BillingStreetAddress).HasMaxLength(500);
            entity.Property(e => e.CustomerProfileId).HasColumnName("CustomerProfileID");
            entity.Property(e => e.MailingAppSuite).HasMaxLength(500);
            entity.Property(e => e.MailingCity).HasMaxLength(500);
            entity.Property(e => e.MailingCountry).HasMaxLength(500);
            entity.Property(e => e.MailingPostalCode).HasMaxLength(500);
            entity.Property(e => e.MailingStateProvince).HasMaxLength(500);
            entity.Property(e => e.MailingStreetAddress).HasMaxLength(500);
            entity.Property(e => e.OtherShippingAppSuite).HasMaxLength(500);
            entity.Property(e => e.OtherShippingCity).HasMaxLength(500);
            entity.Property(e => e.OtherShippingCountry).HasMaxLength(500);
            entity.Property(e => e.OtherShippingPostalCode).HasMaxLength(500);
            entity.Property(e => e.OtherShippingStateProvince).HasMaxLength(500);
            entity.Property(e => e.OtherShippingStreetAddress).HasMaxLength(500);
            entity.Property(e => e.ShippingAppSuite).HasMaxLength(500);
            entity.Property(e => e.ShippingCity).HasMaxLength(500);
            entity.Property(e => e.ShippingCountry).HasMaxLength(500);
            entity.Property(e => e.ShippingPostalCode).HasMaxLength(500);
            entity.Property(e => e.ShippingStateProvince).HasMaxLength(500);
            entity.Property(e => e.ShippingStreetAddress).HasMaxLength(500);

            entity.HasOne(d => d.CustomerProfile).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.CustomerProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerAddress_CustomerProfile");
        });

        modelBuilder.Entity<CustomerProfile>(entity =>
        {
            entity.ToTable("CustomerProfile");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CtgenderId).HasColumnName("CTGenderID");
            entity.Property(e => e.CtpartyTypeId).HasColumnName("CTPartyTypeID");
            entity.Property(e => e.FirstName).IsRequired();
            entity.Property(e => e.FullName).IsRequired();
        });

        modelBuilder.Entity<SystemConfiguration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SystemCo__3214EC27314DFBF9");

            entity.ToTable("SystemConfiguration");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Field)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}