// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.Data.Models;

public partial class CustomerProfile
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string FullName { get; set; }

    public string BussinessName { get; set; }

    public int? CtgenderId { get; set; }

    public int? PartyType { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string AccountNumber { get; set; }

    public string AdditionalInformation { get; set; }

    public string PhoneNumber { get; set; }

    public string MobilePhNo { get; set; }

    public string HomePhNo { get; set; }

    public string BussinessPhNo { get; set; }

    public string EmailAddress { get; set; }

    public string PersonalEmail { get; set; }

    public string BussinessEmail { get; set; }

    public int CreatedBy { get; set; }

    public DateTimeOffset CreatedDateTime { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTimeOffset? UpdatedDateTime { get; set; }
}