// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRM.Data.Models;

public partial class CustomerAddress
{
    public int Id { get; set; }

    public int CustomerProfileId { get; set; }

    public string MailingStreetAddress { get; set; }

    public string MailingAppSuite { get; set; }

    public string MailingCountry { get; set; }

    public string MailingStateProvince { get; set; }

    public string MailingPostalCode { get; set; }

    public string MailingCity { get; set; }

    public string BillingStreetAddress { get; set; }

    public string BillingAppSuite { get; set; }

    public string BillingCountry { get; set; }

    public string BillingStateProvince { get; set; }

    public string BillingPostalCode { get; set; }

    public string BillingCity { get; set; }

    public string ShippingStreetAddress { get; set; }

    public string ShippingAppSuite { get; set; }

    public string ShippingCountry { get; set; }

    public string ShippingStateProvince { get; set; }

    public string ShippingPostalCode { get; set; }

    public string ShippingCity { get; set; }

    public string OtherShippingStreetAddress { get; set; }

    public string OtherShippingAppSuite { get; set; }

    public string OtherShippingCountry { get; set; }

    public string OtherShippingStateProvince { get; set; }

    public string OtherShippingPostalCode { get; set; }

    public string OtherShippingCity { get; set; }

    public virtual CustomerProfile CustomerProfile { get; set; }
}