// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRM.Models;

public partial class CRMDEVContext : DbContext
{
    public CRMDEVContext(DbContextOptions<CRMDEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SystemConfiguration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SystemCo__3214EC27314DFBF9");

            entity.ToTable("SystemConfiguration");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Field)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}